name:                bullshit
version:             0.1.0.0
github:              "feigaoxyz/bullshit"
license:             BSD3
author:              "Fei Gao"
maintainer:          "contact@feigao.org"
copyright:           "Fei Gao"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Misc.

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/feigaoxyz/bullshit#readme>

dependencies:
- base >= 4.7 && < 5
- zero-bullshit
- text
- aeson
- containers

default-extensions:
- OverloadedStrings
- DeriveGeneric
- DeriveAnyClass

library:
  source-dirs: src

executables:
  bullshit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bullshit

tests:
  bullshit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bullshit
